import { icons } from "./icons";
export const viewerMarkup = `
<div class="map-stage"><canvas id="map-canvas" tabindex="0" aria-label="Map: drag to pan; pinch or scroll to zoom. Arrows pan, plus and minus zoom, F fits."></canvas><svg id="map-overlay" class="map-overlay" aria-hidden="true"></svg></div>
<div class="viewer-top"><button class="round-button" id="back" aria-label="Return to library">${icons.arrow}</button><span id="viewer-title"></span><button class="round-button viewer-invert" id="quick-invert" aria-label="Invert map colors" aria-pressed="false">◐</button><button class="round-button" id="toggle-panel" aria-label="Open map tools" aria-expanded="false">☰</button></div>
<div class="viewer-controls"><button id="zoom-out" aria-label="Zoom out">−</button><button id="fit" aria-label="Fit map to screen">${icons.fit}</button><output id="zoom">100%</output><button id="zoom-in" aria-label="Zoom in">+</button><button id="touch-lock" aria-label="Lock map touches" aria-pressed="false">Lock</button></div>
<div id="touch-locked" class="touch-locked" hidden><span>View locked</span><button id="unlock-view">Hold to unlock</button><small id="unlock-hint">Hold for 1 second · keyboard: hold Enter</small></div>
<div id="tool-hint" class="tool-hint" hidden><span id="tool-message"></span><div><button id="tool-center">Use screen center</button><button id="route-undo" hidden>Undo point</button><button id="route-finish" hidden>Finish route</button><button id="tool-cancel">Done</button></div></div>
<aside id="map-panel" class="map-panel" aria-label="Map tools" hidden>
<div class="panel-heading"><h2>Map tools</h2><button id="close-panel" aria-label="Close map tools">✕</button></div>
<p id="save-status" class="save-status" role="status">Saved on device</p>
<section><h3>Orientation & light</h3>
<label class="toggle-row"><span>Lock map rotation</span><input type="checkbox" id="rotation-lock"></label>
<div class="rotation-row"><button id="rotate-left" aria-label="Rotate map left 15 degrees">↶</button><input id="rotation-angle" aria-label="Map rotation" type="range" min="0" max="359" step="1"><button id="rotate-right" aria-label="Rotate map right 15 degrees">↷</button><output id="rotation-value">0°</output></div>
<button id="device-orientation" class="secondary wide">Lock device orientation</button><p id="orientation-message" class="field-help" role="status">Map rotation and phone orientation are separate controls.</p>
<label class="toggle-row"><span>Invert map colors</span><input type="checkbox" id="invert-colors"></label>
<label class="range-label" for="map-dimming">Map light <output id="dimming-value">100%</output></label><input id="map-dimming" class="wide" type="range" min="20" max="100" step="5">
<div class="pan-buttons" aria-label="Pan map"><button data-pan="up" aria-label="Pan up">↑</button><button data-pan="left" aria-label="Pan left">←</button><button data-pan="down" aria-label="Pan down">↓</button><button data-pan="right" aria-label="Pan right">→</button></div></section>
<section><div class="panel-section-heading"><h3>Bookmarks & notes</h3><button id="add-marker" class="text-button">+ Add</button></div><div id="marker-list" class="navigation-list"></div></section>
<section><h3>Estimated position</h3><p class="field-help">Manually placed. No GPS tracking.</p><p id="position-status" class="field-help">No estimated position set.</p><div class="panel-actions"><button id="set-position" class="secondary">Place on map</button><button id="jump-position" class="secondary">Go to estimate</button><button id="clear-position" class="text-button">Clear</button></div></section>
<section><div class="panel-section-heading"><h3>Confirmed checkpoints</h3><button id="add-checkpoint" class="text-button">+ Confirm</button></div><p class="field-help">Record recognized junctions manually. Lines connect your recorded points; they do not establish a traversable path.</p><div id="checkpoint-list" class="navigation-list"></div></section>
<section><div class="panel-section-heading"><h3>Planned routes</h3><button id="add-route" class="text-button">+ Plan</button></div><p class="field-help">Tap along the passages on your map to draw a plan.</p><div id="route-list" class="navigation-list"></div></section>
<section><h3>Offline access</h3><p id="map-offline-status" class="field-help">Not checked yet.</p><button id="verify-current-map" class="secondary wide">Check this map offline</button></section>
</aside>
<p id="viewer-error" class="viewer-error" role="alert" hidden></p>
<dialog id="marker-dialog"><form id="marker-form"><h2 id="marker-dialog-title">Add bookmark</h2><label>Name<input id="marker-label" required maxlength="100" autocomplete="off"></label><label>Kind<select id="marker-kind"><option value="bookmark">Bookmark</option><option value="entrance">Entrance</option><option value="junction">Junction</option><option value="landmark">Landmark</option><option value="note">Note</option></select></label><label>Notes<textarea id="marker-note" maxlength="2000" rows="3"></textarea></label><div class="dialog-actions"><button type="button" id="marker-delete" class="danger" hidden>Delete</button><button type="button" id="marker-cancel" class="secondary">Cancel</button><button type="submit" class="primary">Save</button></div></form></dialog>
<dialog id="name-dialog"><form id="name-form"><h2 id="name-title"></h2><label>Name<input id="name-input" required maxlength="100" autocomplete="off"></label><div class="dialog-actions"><button type="button" id="name-cancel" class="secondary">Cancel</button><button type="submit" class="primary">Save</button></div></form></dialog>`;
